In [82]:
import numpy as np
import time
import matplotlib.pyplot as plt

N = 5   
D = 10
X = np.random.rand(N,D)
print(X)
print(X.shape)

# first function to fill, compute distance matrix using loops
def compute_distance_naive(X):
    N = X.shape[0]      # num of rows
    D = X[0].shape[0]   # num of cols
    print("num of rows: ", N)
    print("num of cols: ", D)
    
    M = np.zeros([N,N])
    for i in range(N):
        for j in range(N):
            xi = X[i,:]
            xj = X[j,:]  
            # expanded formula: np.sqrt(np.sum(xi**2) - 2*np.dot(xi, xj) + np.sum(xj**2))
            # computed matrix are not identical, numerical precision issue?
            # simplified formula: np.sqrt(np.sum((xi - xj)**2))
            dist = np.sqrt(np.sum((xi - xj)**2))  
            M[i,j] = dist

    return M

M = compute_distance_naive(X)
print(M)


[[0.45225518 0.1455663  0.24541647 0.28795071 0.5019253  0.0667941
  0.8319355  0.94282777 0.65226269 0.22055208]
 [0.04386808 0.69877417 0.45863119 0.91500419 0.40411886 0.68274567
  0.17858503 0.3892309  0.03092179 0.43437143]
 [0.43580746 0.79263153 0.81583998 0.00148685 0.29903627 0.3814365
  0.72315685 0.14597641 0.31954432 0.472801  ]
 [0.46660586 0.86485324 0.49552928 0.71382655 0.19209069 0.3420353
  0.97507117 0.51614857 0.86522353 0.18966223]
 [0.38064451 0.86913801 0.53586947 0.01931157 0.44638587 0.11045227
  0.43126317 0.22875261 0.43611518 0.72058787]]
(5, 10)
num of rows:  5
num of cols:  10
[[0.         1.57020939 1.33705204 1.08724927 1.28740121]
 [1.57020939 0.         1.29107642 1.34744319 1.27109422]
 [1.33705204 1.29107642 0.         1.0989098  0.59142428]
 [1.08724927 1.34744319 1.0989098  0.         1.20582852]
 [1.28740121 1.27109422 0.59142428 1.20582852 0.        ]]


In [104]:
import numpy as np
import time
import matplotlib.pyplot as plt

N = 1000
D = 1000
X = np.random.rand(N,D)
print(X)
print(X.shape)

# second function to fill, compute distance matrix without loops
def compute_distance_smart(X):
    N = X.shape[0]  # num of rows
    D = X[0].shape[0]  # num of cols
    
    squared_norms = np.sum(X**2, axis=1)
    print(squared_norms)
    print(squared_norms.shape)  

    # getting zeros for some reason, precision issue?
    M = np.sqrt(squared_norms[:, np.newaxis] + squared_norms[np.newaxis, :] - 2 * np.dot(X, X.T))
    
    return M

M = compute_distance_smart(X)
print(M)

[[0.70568109 0.46483173 0.67644241 ... 0.5150417  0.97740143 0.43507698]
 [0.88722978 0.37823852 0.22859095 ... 0.90115811 0.64606146 0.28017656]
 [0.78577554 0.21322198 0.25942318 ... 0.20830144 0.58425937 0.49018565]
 ...
 [0.62821002 0.99138312 0.25631197 ... 0.32095841 0.62565143 0.86801558]
 [0.21946188 0.38415492 0.46477045 ... 0.15989317 0.08641347 0.08357761]
 [0.85004758 0.1577188  0.55829187 ... 0.45752547 0.53503478 0.28936948]]
(1000, 1000)
[343.42026091 338.97127809 315.07853121 335.99659465 333.04037503
 328.06931862 345.01959351 332.0383193  336.55777887 339.26468914
 340.8802543  341.25513504 347.14487016 332.73746092 342.30971384
 335.45820268 334.44663636 333.39194503 324.24252242 327.89940754
 339.86712384 323.0098392  334.29398778 328.08760168 321.71280847
 343.5423608  339.34124022 338.06418971 341.09204207 313.54728424
 331.68274137 327.25825536 327.3970571  339.7135373  346.76620316
 344.77604284 330.10951422 330.00493108 331.38902232 338.55834267
 338.74966741 3

/tmp/ipykernel_28392/2297562244.py:21: RuntimeWarning: invalid value encountered in sqrt
  M = np.sqrt(squared_norms[:, np.newaxis] + squared_norms[np.newaxis, :] - 2 * np.dot(X, X.T))


In [15]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# print("x: ", x[1,:], sep='\n')
# squared_norms = np.sum(x**2, axis=1)
# print("squared_norms: ", squared_norms[np.newaxis, :], sep='\n')
# Add the vector v to each row of the matrix x with an explicit loop
# for i in range(4):
#     y[i, :] = x[i, :] + v
mean = np.mean(x, axis=0)
print("mean: ", mean, sep='\n')
k = x - mean
print("k: ", k, sep='\n')

# using broadcasting
# y = x + v[np.newaxis, :]  # Add v to each row of x using broadcasting
# print(y)
# y = x + v[:, np.newaxis]  # Add v to each column of x using broadcasting
# print(y)

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]

mean: 
[4. 5. 6.]
k: 
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [133]:
import numpy as np
import time
import matplotlib.pyplot as plt

N = 5   
D = 10
X = np.random.rand(N,D)


# third function to fill, compute correlation matrix using loops
def compute_correlation_naive1(X):
    N = X.shape[0]  # num of rows
    D = X[0].shape[0]  # num of cols

    # use X to create M
    M = np.zeros([D, D])

    # mean of each column with loop
    mu = np.zeros(D)
    for j in range(D):
        mu[j] = (1/N) * np.sum(X[:, j])
    # print("this is mu: ", mu, sep='\n')

    # covariance matrix with loops
    S = np.zeros([D, D])
    for i in range(D):
        for j in range(D):
            xi = X[:, i]
            xj = X[:, j]
            covariance = (1 / (N - 1)) * np.sum((xi - mu[i]) * (xj - mu[j]))
            S[i, j] = covariance
    # print("this is covariance: ", S, sep='\n')

    # standard deviation
    sigma = np.zeros(D)
    for i in range(D):
        sigma[i] = np.sqrt(S[i, i])  
    print("this is sigma: ", sigma, sep='\n')

    # correlation matrix with loop  
    for i in range(D):
        for j in range(D):
            if sigma[i] * sigma[j] != 0:
                corr = S[i, j] / (sigma[i] * sigma[j])
            else:
                corr = 0
            M[i, j] = corr

    return M

k = compute_correlation_naive1(X)
# print("this is k: ", k, sep='\n')

# fourth function to fill, compute correlation matrix without loops
def compute_correlation_smart(X):
    N = X.shape[0]  # num of rows
    D = X[0].shape[0]  # num of cols

    # use X to create M
    M = np.zeros([D, D])

    # mean of each column
    mu = np.mean(X, 0)
    # print("this is mu: ", mu, sep='\n')

    # covariance matrix without loops
    covariance = np.dot((X - mu).T, (X - mu)) / (N - 1.0)
    # print("this is covariance: ", covariance, sep='\n')

    # standard deviation
    sigma = np.sqrt(covariance.diagonal())
    print("this is sigma: ", sigma, sep='\n')

    # correlation matrix without loops
    sigma_outer = np.outer(sigma, sigma)
    M = covariance / sigma_outer

    return M
M = compute_correlation_smart(X)
# print("this is M: ", M, sep='\n')

assert np.allclose(M, k, atol=1e-06)

this is sigma: 
[0.23986096 0.12643223 0.19086252 0.31243632 0.3386688  0.3259301
 0.3124734  0.38913851 0.28922018 0.31463969]
this is sigma: 
[0.23986096 0.12643223 0.19086252 0.31243632 0.3386688  0.3259301
 0.3124734  0.38913851 0.28922018 0.31463969]


In [135]:
import numpy as np

# create a 2D array with 10 rows and 5 columns
array = np.random.rand(10)

# print the shape of the array
print("Shape of the array:", array.shape)

# print the array
print("Array:", array)

print("expanded dims axis=0: ", np.expand_dims(array, axis=0).shape, np.expand_dims(array, axis=0), sep='\n')
print("expanded dims axis=1: ", np.expand_dims(array, axis=1).shape, np.expand_dims(array, axis=1), sep='\n')

Shape of the array: (10,)
Array: [0.47766063 0.85463036 0.29782219 0.40378888 0.98427319 0.1033458
 0.75057363 0.87241522 0.02913915 0.59102512]
expanded dims axis=0: 
(1, 10)
[[0.47766063 0.85463036 0.29782219 0.40378888 0.98427319 0.1033458
  0.75057363 0.87241522 0.02913915 0.59102512]]
expanded dims axis=1: 
(10, 1)
[[0.47766063]
 [0.85463036]
 [0.29782219]
 [0.40378888]
 [0.98427319]
 [0.1033458 ]
 [0.75057363]
 [0.87241522]
 [0.02913915]
 [0.59102512]]


In [5]:
import numpy as np
from sklearn.datasets import load_breast_cancer, load_digits, load_iris
X = load_iris()['data']
print(X.shape)

ModuleNotFoundError: No module named 'sklearn'